# Site settings
title: "Kumu's Blog"
description: >
  Kumu's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.opskumu.com" # the base hostname & protocol for your site

author:
  fullname: kumu
  github: opskumu
  # twitter:
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    toc_levels: 1..3
    default_lang: bash
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
#     highlighter: pygments
permalink: /:title.html
comments:
    provider: duoshuo
    duoshuo:
        short_name: kumu
